# This is a file for you to write an un-named mutation.
# Only one un-named mutation is allowed per file.
mutation {
  user_insert(
    data: {
      clerkId: "user_3D8JSOjW3VISM9fOcHUXyKaGO4c"
      email: "jonathanmoreradev@gmail.com"
      imageUrl: "https://lh3.googleusercontent.com/a/ACg8ocLrgRW6rPVg_tX12RsaeCDDUJ-Aux0XNGzjSlWvWnbfu98qBw=s1000-c"
      username: "jonathanmoreradev"
    }
  )
}
